-- Shri Kalyan Matka - Supabase Database Schema

-- 1. Realtime Sync Table (Syncs full state across all devices & admin live)
create table if not exists public.wordgame_state (
  id text primary key default 'current',
  state jsonb not null,
  version integer not null default 1,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS & policies for state sync
alter table public.wordgame_state enable row level security;

drop policy if exists "Allow all select on wordgame_state" on public.wordgame_state;
create policy "Allow all select on wordgame_state" on public.wordgame_state for select using (true);

drop policy if exists "Allow all insert on wordgame_state" on public.wordgame_state;
create policy "Allow all insert on wordgame_state" on public.wordgame_state for insert with check (true);

drop policy if exists "Allow all update on wordgame_state" on public.wordgame_state;
create policy "Allow all update on wordgame_state" on public.wordgame_state for update using (true);

-- Enable Supabase Realtime publication
do $$
begin
  if not exists (
    select 1 from pg_publication_tables 
    where pubname = 'supabase_realtime' and tablename = 'wordgame_state'
  ) then
    alter publication supabase_realtime add table public.wordgame_state;
  end if;
exception when others then
  null;
end $$;

-- 2. Structured Relational Tables (For direct querying, analytics & backups)

-- Users table
create table if not exists public.users (
  id bigint primary key generated by default as identity,
  name text not null,
  mobile text unique not null,
  password text not null,
  email text default '',
  balance numeric(12, 2) default 0,
  status text default 'active',
  betting boolean default true,
  joined text,
  last_login text,
  logged_in boolean default false,
  bank jsonb default '{}'::jsonb,
  paytm text default '',
  phonepe text default '',
  gpay text default '',
  upi text default '',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Games / Markets table
create table if not exists public.games (
  id bigint primary key generated by default as identity,
  cat text not null,
  name text not null,
  open_time text not null,
  close_time text not null,
  active boolean default true,
  off_days integer[] default '{}',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Bids table
create table if not exists public.bids (
  id bigint primary key generated by default as identity,
  user_id bigint references public.users(id) on delete cascade,
  game_id bigint references public.games(id) on delete cascade,
  type text not null,
  session text,
  value text not null,
  amount numeric(12, 2) not null,
  rate numeric(12, 2) not null,
  date text not null,
  time text not null,
  status text default 'pending',
  win numeric(12, 2) default 0,
  settled_by text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Results table
create table if not exists public.results (
  id bigint primary key generated by default as identity,
  game_id bigint references public.games(id) on delete cascade,
  date text not null,
  open_pana text,
  open_at text,
  close_pana text,
  close_at text,
  jodi text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Transactions / Wallet Statement table
create table if not exists public.transactions (
  id bigint primary key generated by default as identity,
  user_id bigint references public.users(id) on delete cascade,
  type text not null,
  dir text not null check (dir in ('cr', 'dr')),
  amount numeric(12, 2) not null,
  date text not null,
  time text not null,
  status text default 'success',
  remark text default '',
  mode text,
  utr text,
  pay_to text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- App Settings table
create table if not exists public.app_settings (
  id integer primary key default 1,
  data jsonb not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS on relational tables
alter table public.users enable row level security;
alter table public.games enable row level security;
alter table public.bids enable row level security;
alter table public.results enable row level security;
alter table public.transactions enable row level security;
alter table public.app_settings enable row level security;

-- Basic open policies (can be refined with Supabase Auth if needed)
drop policy if exists "Allow all on users" on public.users;
create policy "Allow all on users" on public.users for all using (true) with check (true);

drop policy if exists "Allow all on games" on public.games;
create policy "Allow all on games" on public.games for all using (true) with check (true);

drop policy if exists "Allow all on bids" on public.bids;
create policy "Allow all on bids" on public.bids for all using (true) with check (true);

drop policy if exists "Allow all on results" on public.results;
create policy "Allow all on results" on public.results for all using (true) with check (true);

drop policy if exists "Allow all on transactions" on public.transactions;
create policy "Allow all on transactions" on public.transactions for all using (true) with check (true);

drop policy if exists "Allow all on app_settings" on public.app_settings;
create policy "Allow all on app_settings" on public.app_settings for all using (true) with check (true);
